// Package services — Rule-based GIFT question generator.
// No external AI API is used. Questions are generated by analysing the
// source text: splitting into sentences, extracting key terms, facts and
// definitions, then applying templates for each GIFT question type.
package services

import (
	"fmt"
	"math/rand"
	"regexp"
	"strings"
	"time"
	"unicode"

	"github.com/google/uuid"
	"github.com/youorg/moodle-gift-generator/internal/models"
)

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

func GenerateQuestions(req *models.GenerateRequest, userID string) ([]models.Question, string, error) {
	if len(req.QuestionTypes) == 0 {
		req.QuestionTypes = []string{"multiple_choice"}
	}
	if req.Count == 0 {
		req.Count = 5
	}
	if req.Count > 30 {
		req.Count = 30
	}
	if req.Language == "" {
		req.Language = "vi"
	}

	src := strings.TrimSpace(req.SourceText)
	if src == "" {
		return nil, "", fmt.Errorf("source text is empty")
	}

	rng := rand.New(rand.NewSource(time.Now().UnixNano()))

	sents := extractSentences(src)
	terms := extractKeyTerms(src)
	defs  := extractDefinitions(src)

	if len(sents) == 0 {
		return nil, "", fmt.Errorf("không tìm thấy câu nào trong văn bản đầu vào")
	}

	type genFn func() (string, string, string)
	var pool []genFn

	for _, qt := range req.QuestionTypes {
		qt := qt
		switch qt {
		case "multiple_choice":
			pool = append(pool, func() (string, string, string) {
				return buildMC(sents, terms, rng, req.Language)
			})
		case "true_false":
			pool = append(pool, func() (string, string, string) {
				return buildTF(sents, rng, req.Language)
			})
		case "short_answer":
			pool = append(pool, func() (string, string, string) {
				return buildSA(sents, terms, rng, req.Language)
			})
		case "essay":
			pool = append(pool, func() (string, string, string) {
				return buildEssay(sents, defs, rng, req.Language)
			})
		case "matching":
			pool = append(pool, func() (string, string, string) {
				return buildMatching(terms, defs, rng, req.Language)
			})
		}
	}

	if len(pool) == 0 {
		return nil, "", fmt.Errorf("no valid question types selected")
	}

	var questions []models.Question
	var giftLines []string

	giftLines = append(giftLines,
		"// GIFT format — generated by rule-based engine",
		fmt.Sprintf("// Source: %d chars, %d sentences, %d key terms", len(src), len(sents), len(terms)),
		"",
	)

	seenBlocks := map[string]bool{}
	maxAttempts := req.Count * 10
	attempts    := 0
	idx         := 0

	for len(questions) < req.Count && attempts < maxAttempts {
		attempts++
		fn := pool[idx%len(pool)]
		idx++

		qtype, title, block := fn()
		block = strings.TrimSpace(block)
		if block == "" || seenBlocks[block] {
			continue
		}
		seenBlocks[block] = true

		questions = append(questions, models.Question{
			ID:         uuid.New().String(),
			UserID:     userID,
			BankID:     req.BankID,
			Type:       qtype,
			Title:      title,
			Content:    block,
			SourceText: src,
			Language:   req.Language,
			Tags:       []string{},
		})
		giftLines = append(giftLines, block, "")
	}

	if len(questions) == 0 {
		return nil, "", fmt.Errorf("không thể tạo câu hỏi — hãy thử văn bản dài hơn hoặc có cấu trúc rõ ràng hơn")
	}

	return questions, strings.Join(giftLines, "\n"), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Text analysis
// ─────────────────────────────────────────────────────────────────────────────

func extractSentences(text string) []string {
	text = regexp.MustCompile(`[ \t]+`).ReplaceAllString(text, " ")
	splitter := regexp.MustCompile(`[.!?。！？]\s+`)
	raw := splitter.Split(text, -1)

	seen := map[string]bool{}
	var out []string

	add := func(s string) {
		s = strings.TrimSpace(s)
		r := []rune(s)
		if len(r) < 20 || len(r) > 400 || seen[s] {
			return
		}
		for _, ch := range s {
			if unicode.IsLetter(ch) {
				seen[s] = true
				out = append(out, s)
				return
			}
		}
	}

	for _, s := range raw {
		add(s)
	}
	for _, line := range strings.Split(text, "\n") {
		add(line)
	}
	return out
}

type KeyTerm struct {
	Term string
	Desc string
}

func extractKeyTerms(text string) []KeyTerm {
	seen := map[string]bool{}
	var terms []KeyTerm

	add := func(term, desc string) {
		term = strings.TrimSpace(term)
		key  := strings.ToLower(term)
		if term == "" || seen[key] || len([]rune(term)) < 3 || len([]rune(term)) > 60 {
			return
		}
		seen[key] = true
		terms = append(terms, KeyTerm{term, strings.TrimSpace(desc)})
	}

	patterns := []*regexp.Regexp{
		regexp.MustCompile(`([A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐ][^\n.!?]{2,40})\s+(?:là|là một|được gọi là)\s+([^.!?\n]{5,80})`),
		regexp.MustCompile(`([A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐ][^\n.!?]{2,40})\s+(?:is|are|refers to|means)\s+([^.!?\n]{5,80})`),
		regexp.MustCompile(`\*\*([^*]{3,50})\*\*`),
		regexp.MustCompile(`_([^_]{3,50})_`),
	}

	for _, re := range patterns {
		for _, m := range re.FindAllStringSubmatch(text, -1) {
			if len(m) >= 3 {
				add(m[1], m[2])
			} else if len(m) >= 2 {
				add(m[1], "")
			}
		}
	}

	// Capitalised phrase appearing 2+ times
	capRe  := regexp.MustCompile(`\b([A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐ][a-zàáâãèéêìíòóôõùúýăđA-Z]+(?:\s+[A-Za-zàáâãèéêìíòóôõùúýăđ]+){1,3})\b`)
	freq   := map[string]int{}
	for _, m := range capRe.FindAllString(text, -1) {
		freq[m]++
	}
	for term, cnt := range freq {
		if cnt >= 2 {
			add(term, "")
		}
	}

	return terms
}

type definition struct {
	Term string
	Def  string
}

func extractDefinitions(text string) []definition {
	seen := map[string]bool{}
	var defs []definition

	patterns := []*regexp.Regexp{
		regexp.MustCompile(`([A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐ][^\n.!?]{2,35})\s+(?:là|là một)\s+([^.!?\n]{8,80})[.!?]`),
		regexp.MustCompile(`([A-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐ][^\n.!?]{2,35})\s+(?:is|refers to|means)\s+([^.!?\n]{8,80})[.!?]`),
	}
	for _, re := range patterns {
		for _, m := range re.FindAllStringSubmatch(text, -1) {
			if len(m) < 3 {
				continue
			}
			term := strings.TrimSpace(m[1])
			def  := strings.TrimSpace(m[2])
			r    := []rune(def)
			if len(r) > 60 {
				def = string(r[:60]) + "..."
			}
			key := strings.ToLower(term)
			if !seen[key] && len([]rune(term)) >= 3 && len([]rune(def)) >= 5 {
				seen[key] = true
				defs = append(defs, definition{term, def})
			}
		}
	}
	return defs
}

// ─────────────────────────────────────────────────────────────────────────────
// Question builders
// ─────────────────────────────────────────────────────────────────────────────

func buildMC(sents []string, terms []KeyTerm, rng *rand.Rand, lang string) (string, string, string) {
	if len(sents) == 0 {
		return "", "", ""
	}

	sent := sents[rng.Intn(len(sents))]

	var chosenTerm KeyTerm
	for _, t := range terms {
		if strings.Contains(strings.ToLower(sent), strings.ToLower(t.Term)) {
			chosenTerm = t
			break
		}
	}

	var question, correct string
	var distractors []string

	if chosenTerm.Term != "" {
		question = replaceFirstCI(sent, chosenTerm.Term, "___")
		correct  = chosenTerm.Term
		for _, t := range terms {
			if strings.ToLower(t.Term) != strings.ToLower(chosenTerm.Term) {
				distractors = append(distractors, t.Term)
			}
		}
	} else {
		if lang == "vi" {
			question = "Phát biểu nào sau đây phản ánh đúng nội dung đoạn văn?"
		} else {
			question = "Which of the following best reflects the passage?"
		}
		correct = truncate(sent, 80)
		shuffled := make([]string, len(sents))
		copy(shuffled, sents)
		rng.Shuffle(len(shuffled), func(i, j int) { shuffled[i], shuffled[j] = shuffled[j], shuffled[i] })
		for _, s := range shuffled {
			if s != sent {
				distractors = append(distractors, truncate(s, 80))
			}
		}
	}

	if len(distractors) < 3 {
		distractors = append(distractors, genericDistractors(lang, 3-len(distractors))...)
	}
	rng.Shuffle(len(distractors), func(i, j int) { distractors[i], distractors[j] = distractors[j], distractors[i] })
	distractors = distractors[:clamp(len(distractors), 3)]

	title := truncate(question, 60)
	var sb strings.Builder
	fmt.Fprintf(&sb, "::%s::%s {\n", title, question)
	fmt.Fprintf(&sb, "=%s\n", escapeGIFT(correct))
	for _, d := range distractors {
		fmt.Fprintf(&sb, "~%s\n", escapeGIFT(d))
	}
	sb.WriteString("}")
	return "multiple_choice", title, sb.String()
}

func buildTF(sents []string, rng *rand.Rand, lang string) (string, string, string) {
	if len(sents) == 0 {
		return "", "", ""
	}
	sent := truncate(sents[rng.Intn(len(sents))], 150)
	isTrue := rng.Float32() < 0.7
	answer := "TRUE"
	stmt   := sent
	if !isTrue {
		answer = "FALSE"
		stmt   = negateStatement(sent, lang)
	}
	title := truncate(stmt, 60)
	return "true_false", title, fmt.Sprintf("::%s::%s { %s }", title, stmt, answer)
}

func buildSA(sents []string, terms []KeyTerm, rng *rand.Rand, lang string) (string, string, string) {
	if len(terms) == 0 || len(sents) == 0 {
		return "", "", ""
	}
	shuffledS := make([]string, len(sents))
	copy(shuffledS, sents)
	rng.Shuffle(len(shuffledS), func(i, j int) { shuffledS[i], shuffledS[j] = shuffledS[j], shuffledS[i] })

	shuffledT := make([]KeyTerm, len(terms))
	copy(shuffledT, terms)
	rng.Shuffle(len(shuffledT), func(i, j int) { shuffledT[i], shuffledT[j] = shuffledT[j], shuffledT[i] })

	for _, sent := range shuffledS {
		for _, t := range shuffledT {
			if strings.Contains(strings.ToLower(sent), strings.ToLower(t.Term)) {
				blanked := replaceFirstCI(sent, t.Term, "___")
				title   := truncate(blanked, 60)
				answers := []string{t.Term}
				if lower := strings.ToLower(t.Term); lower != t.Term {
					answers = append(answers, lower)
				}
				var sb strings.Builder
				fmt.Fprintf(&sb, "::%s::%s {", title, blanked)
				for _, a := range answers {
					fmt.Fprintf(&sb, "\n=%s", escapeGIFT(a))
				}
				sb.WriteString("\n}")
				return "short_answer", title, sb.String()
			}
		}
	}
	return "", "", ""
}

func buildEssay(sents []string, defs []definition, rng *rand.Rand, lang string) (string, string, string) {
	var stem string
	if len(defs) > 0 {
		d := defs[rng.Intn(len(defs))]
		if lang == "vi" {
			stem = fmt.Sprintf("Hãy giải thích khái niệm \"%s\" và nêu ý nghĩa của nó.", d.Term)
		} else {
			stem = fmt.Sprintf("Explain the concept of \"%s\" and discuss its significance.", d.Term)
		}
	} else if len(sents) > 0 {
		sent := truncate(sents[rng.Intn(len(sents))], 100)
		if lang == "vi" {
			stem = fmt.Sprintf("Hãy phân tích và trình bày ý nghĩa của: \"%s\"", sent)
		} else {
			stem = fmt.Sprintf("Analyse and explain the significance of: \"%s\"", sent)
		}
	} else {
		return "", "", ""
	}
	title := truncate(stem, 60)
	return "essay", title, fmt.Sprintf("::%s::%s {}", title, stem)
}

func buildMatching(terms []KeyTerm, defs []definition, rng *rand.Rand, lang string) (string, string, string) {
	type pair struct{ term, answer string }
	var pairs []pair
	for _, d := range defs {
		pairs = append(pairs, pair{d.Term, d.Def})
	}
	for _, t := range terms {
		if t.Desc != "" {
			pairs = append(pairs, pair{t.Term, t.Desc})
		}
	}
	if len(pairs) < 3 {
		return "", "", ""
	}
	rng.Shuffle(len(pairs), func(i, j int) { pairs[i], pairs[j] = pairs[j], pairs[i] })
	selected := pairs[:clamp(len(pairs), 5)]

	var title string
	if lang == "vi" {
		title = "Nối cặp khái niệm"
	} else {
		title = "Match the concepts"
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "::%s::%s {\n", title, title)
	for _, p := range selected {
		fmt.Fprintf(&sb, "=%s -> %s\n", escapeGIFT(truncate(p.term, 40)), escapeGIFT(truncate(p.answer, 60)))
	}
	sb.WriteString("}")
	return "matching", title, sb.String()
}

// ─────────────────────────────────────────────────────────────────────────────
// Utility
// ─────────────────────────────────────────────────────────────────────────────

func negateStatement(sent, lang string) string {
	if lang == "vi" {
		for _, v := range []string{" là ", " có ", " được ", " sẽ "} {
			if idx := strings.Index(sent, v); idx >= 0 {
				return sent[:idx] + strings.Replace(v, " ", " không ", 1) + sent[idx+len(v):]
			}
		}
		return "Sai: " + sent
	}
	for _, aux := range []string{" is ", " are ", " was ", " were ", " has ", " have ", " can ", " will "} {
		if idx := strings.Index(sent, aux); idx >= 0 {
			return sent[:idx] + strings.Replace(aux, " ", " not ", 1) + sent[idx+len(aux):]
		}
	}
	return "It is incorrect that: " + sent
}

func genericDistractors(lang string, count int) []string {
	en := []string{"None of the above", "All of the above", "Cannot be determined", "The opposite is true", "Not mentioned in the text"}
	vi := []string{"Không có đáp án nào đúng", "Tất cả đều đúng", "Không thể xác định", "Điều ngược lại", "Không được đề cập trong văn bản"}
	src := en
	if lang == "vi" {
		src = vi
	}
	if count > len(src) {
		count = len(src)
	}
	return src[:count]
}

func replaceFirstCI(s, old, newStr string) string {
	lower    := strings.ToLower(s)
	lowerOld := strings.ToLower(old)
	idx := strings.Index(lower, lowerOld)
	if idx < 0 {
		return s
	}
	return s[:idx] + newStr + s[idx+len(old):]
}

func escapeGIFT(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "~", "\\~")
	s = strings.ReplaceAll(s, "=", "\\=")
	s = strings.ReplaceAll(s, "{", "\\{")
	s = strings.ReplaceAll(s, "}", "\\}")
	s = strings.ReplaceAll(s, "#", "\\#")
	return s
}

func truncate(s string, max int) string {
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	return string(r[:max]) + "..."
}

// clamp returns n if n < max, else max (min 1)
func clamp(n, max int) int {
	if n < max {
		return n
	}
	return max
}

// ─────────────────────────────────────────────────────────────────────────────
// GIFT import parser (unchanged)
// ─────────────────────────────────────────────────────────────────────────────

func parseGIFTToQuestions(giftText, userID, bankID, language, sourceText string) []models.Question {
	var questions []models.Question
	for _, block := range splitGIFTBlocks(giftText) {
		block = strings.TrimSpace(block)
		if block == "" {
			continue
		}
		q := models.Question{
			ID: uuid.New().String(), UserID: userID, BankID: bankID,
			Content: block, SourceText: sourceText, Language: language, Tags: []string{},
		}
		q.Type  = detectGIFTType(block)
		q.Title = extractGIFTTitle(block)
		if q.Title == "" {
			q.Title = fmt.Sprintf("Question %s", q.ID[:8])
		}
		questions = append(questions, q)
	}
	return questions
}

func splitGIFTBlocks(text string) []string {
	var blocks []string
	var cur strings.Builder
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "//") {
			continue
		}
		if line == "" {
			if cur.Len() > 0 {
				blocks = append(blocks, cur.String())
				cur.Reset()
			}
			continue
		}
		cur.WriteString(line + "\n")
	}
	if cur.Len() > 0 {
		blocks = append(blocks, cur.String())
	}
	return blocks
}

func detectGIFTType(block string) string {
	if (strings.Contains(block, "TRUE") || strings.Contains(block, "FALSE")) && !strings.Contains(block, "~") {
		return "true_false"
	}
	if strings.Contains(block, "->") {
		return "matching"
	}
	if strings.Contains(block, "~") {
		return "multiple_choice"
	}
	if extractGIFTContent(block) == "" {
		return "essay"
	}
	return "short_answer"
}

func extractGIFTTitle(block string) string {
	if strings.HasPrefix(block, "::") {
		if end := strings.Index(block[2:], "::"); end > 0 {
			return strings.TrimSpace(block[2 : end+2])
		}
	}
	return truncate(stripGIFTFormatting(block), 60)
}

func extractGIFTContent(block string) string {
	s := strings.Index(block, "{")
	e := strings.LastIndex(block, "}")
	if s < 0 || e < 0 {
		return ""
	}
	return strings.TrimSpace(block[s+1 : e])
}

func stripGIFTFormatting(block string) string {
	if strings.HasPrefix(block, "::") {
		if end := strings.Index(block[2:], "::"); end > 0 {
			block = block[end+4:]
		}
	}
	if s := strings.Index(block, "{"); s > 0 {
		block = block[:s]
	}
	return strings.TrimSpace(block)
}

func ParseGIFTFile(content, userID, bankID string) ([]models.Question, error) {
	qs := parseGIFTToQuestions(content, userID, bankID, "vi", "")
	if len(qs) == 0 {
		return nil, fmt.Errorf("no valid GIFT questions found in the file")
	}
	return qs, nil
}
